### ISSUE TITLE
what is the difference between giltene/wrk2 and kinvolk/wrk2?

### ISSUE THREAD

**Issue by kason-huang** [kinvolk/service-mesh-benchmark#12]
The experiment use the kinvolk/wrk2 to build the wrk2 image. I would like to know what is the main difference between kinvolk/wrk2 and giltene/wrk2.
Thanks.

**Comment by invidian** [comment]
The blog post about the benchmarks mentions changes we've made: https://kinvolk.io/blog/2019/05/performance-benchmark-analysis-of-istio-and-linkerd/
> For the purpose of this benchmark, we extended the capabilities of wrk2, adding the handling of multiple server addresses and multiple HTTP resource paths. We do not consider our work a fork and will work with upstream to get our changes merged.

Perhaps @t-lo can say more about it :)

**Comment by t-lo** [comment]
Please pardon the long delay.

Our fork includes a number of experimental extensions that makes wrk2 usable for benchmarking multiple endpoints at once. We aim to include the changes with Gil Tene's upstream eventually.
