### ISSUE TITLE
bookinfo app is slow investigate if it is true for different scenarios

### ISSUE THREAD

**Issue by surajssd** [kinvolk/service-mesh-benchmark#18]
> On a side note, I've noticed during benchmarking to verify this PR that the `bookinfo` app is super slow. Even on a [n2.large](https://www.packet.com/cloud/servers/n2-xlarge/) I could barely push the RPS beyond 50. The `emojivoto` app can easily handle 5000 RPS. 

@t-lo 's observation from https://github.com/kinvolk/service-mesh-benchmark/pull/15#issuecomment-657558253

**Comment by t-lo** [comment]
Closed as incomplete - we settled with using emojivoto.
