### ISSUE TITLE
setup-cluster.sh fails when provisioning into a new, empty Packet project

### ISSUE THREAD

**Issue by t-lo** [kinvolk/service-mesh-benchmark#3]
When provisioning into a _new, empty_ Packet project, `scripts/*/setup-cluster.sh` fails with:
```
Error: Error refreshing state: 1 error(s) occurred:

* data.packet_precreated_ip_block.ipv4: 1 error(s) occurred:

* data.packet_precreated_ip_block.ipv4: data.packet_precreated_ip_block.ipv4: Could not find matching reserved block, all IPs were []
```

As a temporary work-around until this issue has been addressed, please manually create a temporary server via the Packet web interface, then run `setup-cluster.sh`. You can then delete the server you've created manually.

**Comment by invidian** [comment]
Bummer, I thought `packet_precreated_ip_block` will still work even if ipv4 block does not exist. Maybe we should switch to use https://www.terraform.io/docs/providers/packet/r/reserved_ip_block.html instead.

**Comment by t-lo** [comment]
Resolving since it affects only v1.0 which has since been superseded by v2.0 of the benchmark automation.
